### ISSUE TITLE
Certain filenames seem to be mistakenly found as not on local machine

### ISSUE THREAD

**Issue by dcowan-e-courier** [euan-forrester/vue-cli-plugin-s3-deploy-cleanup#10]
Started with an empty bucket and on first deploy the plugin failed.  I believe it is due to problems with some filenames.  I believe it may be due to filenames with percent signs in them.  The log file is attached.  An example file is 

img/checkbox-01%402x.d5554fe4.png

[plugin.log](https://github.com/euan-forrester/vue-cli-plugin-s3-deploy-cleanup/files/6862808/plugin.log)

**Comment by euan-forrester** [comment]
Hm thank you! I’m out of town at the moment but I’ll take a look when I’m back!

**Comment by euan-forrester** [comment]
@dcowan-e-courier this is fixed in version `1.0.4` -- thanks for reporting the issue (and the helpful log files!) and sorry about the trouble!

**Comment by dcowan-e-courier** [comment]
Thanks @euan-forrester confirmed fixed for my use case

**Comment by euan-forrester** [comment]
Awesome, and thanks for confirming!
