### ISSUE TITLE
node 18

### ISSUE THREAD

**Issue by steveatkoan** [euan-forrester/vue-cli-plugin-s3-deploy-cleanup#13]
Hi
Any chance of a version bump to allow node v18+?
thanks!

**Comment by euan-forrester** [comment]
Yep, for sure -- I was just thinking I needed to bump the versions again. Is the issue that `@vue/cli-shared-utils` needs to be `5.0.x`?

I'm away from my computer a lot today, but I'll try to do it today or tomorrow.

Thanks for using it, and for dropping me a line!

**Comment by steveatkoan** [comment]
Cheers! I see
```error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.2.0"```

**Comment by euan-forrester** [comment]
Hm I’m confused then!

The requirements of this module are listed as >= 12, so I don’t know why 8
and 10 are allowed and 18 is not:
https://github.com/euan-forrester/vue-cli-plugin-s3-deploy-cleanup/blob/main/package.json#L37

Is the problem maybe with your yarn.lock (or similar) file?
https://stackoverflow.com/questions/56617209/the-engine-node-is-incompatible-with-this-module

**Comment by steveatkoan** [comment]
mm yeah. maybe its a deeper dependency problem: the error is from achrinza/node-ipc. So i wondered if you were able to update yours to pull more recent dependencies whether this would go away? (Apologies if this assumption is incorrect: this is my first major vue project. I've been in the PHP world for 20 years: dependency management is very different there)

**Comment by euan-forrester** [comment]
yeah no worries -- I need to update them anyway! in the meantime, does the error go away if you (just as a test) delete your yarn.lock file and do another yarn install?

**Comment by steveatkoan** [comment]
no. i still have the error after deleting yarn.lock and re installing

**Comment by euan-forrester** [comment]
heh I assume that was a typo -- log vs lock? but no worries, I'll update all the deps asap!

**Comment by euan-forrester** [comment]
Okay, can you give it another go? I published a new version `1.1.0` which has all its dependencies updated to their latest versions. You can check out the diffs here: https://github.com/euan-forrester/vue-cli-plugin-s3-deploy-cleanup/pull/14

**Comment by steveatkoan** [comment]
thanks. I still see the error message. I guess some deeply nested package depends on achrinza/node-ipc:9.2.2. Latest is 10.1.6 which fixes the problem. Is there a way to follow the dependency constraints tree up for a package that is not installed?

**Comment by euan-forrester** [comment]
I saw that the version of that package got updated to that version in the `yarn.lock` file in this package that was generated by this update (it was a little earlier before). So yeah, 9.2.2 is coming from this package (and maybe others). 

I don't really follow your question (maybe take a look through the new yarn.lock file in this package?) and I have to run for dinner, but I might look at the option in that stackoverflow link to have yarn disregard the node version specified.

But unless I missed a newer version of any of the dependencies here, I'm not sure if there's more I can help with here other than giving generic dependency advice.

**Comment by steveatkoan** [comment]
appreciated your help. Thank you.

**Comment by euan-forrester** [comment]
No problem!

BTW I just found this:

```
% yarn why @achrinza/node-ipc      
yarn why v1.22.18
[1/4] 🤔  Why do we have the module "@achrinza/node-ipc"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@achrinza/node-ipc@9.2.2"
info Reasons this module exists
   - "@vue#cli-shared-utils" depends on it
   - Hoisted from "@vue#cli-shared-utils#@achrinza#node-ipc"
info Disk size without dependencies: "212KB"
info Disk size with unique dependencies: "308KB"
info Disk size with transitive dependencies: "344KB"
info Number of shared dependencies: 3
✨  Done in 0.17s.
```

And `@vue/cli-shared-utils` is at its latest version now (`5.0.4`). It's been a while since I wrote this package, but I believe that it has to depend on the vue cli shared utils, and that most plugins in the vue ecosystem will also have to.

If you haven't already, you may want to install `nvm` to help manage node versions on your local machine as you try to find one that works. And then maybe add a `.nvmrc` file to your repo once you find one.

I hope you still find this plugin useful (it's part of my CD pipeline), and if you do please leave a star!

Thanks for the impetus to get these deps updated!
