### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by javi-p-nt** [euan-forrester/vue-cli-plugin-s3-deploy-cleanup#6]
When I try to execute the cleanup I get it. It would be possible because the default aws profile it's not the same that the bucket? 
I've fullaccess to s3.

**Comment by euan-forrester** [comment]
Yeah that seems like the most likely cause. The vue-cli-plugin-deploy plugin also uses the default aws profile, so I'm not sure that adding an option to specify a different profile here makes sense. Sounds like maybe you have a permissions misconfiguration if you're able to use that plugin to upload to the bucket, but unable to use this one to add tags?

**Comment by chuntin** [comment]
Hi, that's it. I can deploy with another profile previously selected in the plugin configuration but in this plugin I can't select a different profile for AWS. I use a lot of AWS accounts and I would need these feature. I think is very important. Anyway thanks for your plugin.

**Comment by euan-forrester** [comment]
Oh, I'm very sorry: you're right, the vue-cli-plugin-deploy plugin does allow you to configure the aws profile. I'll add that support for this plugin as well. Thanks for pointing that out!

**Comment by euan-forrester** [comment]
There's currently a workaround if you set the `AWS_PROFILE` env var when running the plugin. I'm working on adding support for the various AWS config values that the vue-cli-plugin-deploy takes

**Comment by javi-p-nt** [comment]
I'll wait for this enhacement. I use awsProfile in S3D but only works in these plugin by vue.config file or by env var.

**Comment by euan-forrester** [comment]
This should be fixed by https://github.com/euan-forrester/vue-cli-plugin-s3-deploy-cleanup/pull/7 and I published it as version 1.0.2. Please let me know if you have any more problems and thanks for pointing out this issue!
