### ISSUE TITLE
Minimum node version

### ISSUE THREAD

**Issue by VinceG** [euan-forrester/vue-cli-plugin-s3-deploy-cleanup#8]
Hey,

Is there a reason why the minimum node version is 14?

**Comment by euan-forrester** [comment]
Not especially -- it was just the one I tested with so I can't guarantee anything else. I think the only stuff I used that's "fancy" are classes and async/await which have both been around for a bunch of node versions. 

If you find an earlier version that seems to work fine I'm happy to bump that requirement down!

**Comment by VinceG** [comment]
@euan-forrester Awesome, thank you. I'll give this a shot on 12 and see if that'll work

**Comment by nmosnaim** [comment]
I can confirm that it works correctly with Node 12.x!

**Comment by euan-forrester** [comment]
@nmosnaim Thank you! I just published version 1.0.3 that downgrades the required version to 12

@VinceG Does this work better for you now?

**Comment by VinceG** [comment]
That works, thank you!
